import React, { useState, useEffect } from 'react';
import { ItineraryOption } from './types';
import { generateItinerary } from './services/geminiService';
import TripInput from './components/TripInput';
import ItineraryDisplay from './components/ItineraryDisplay';
import LoadingSpinner from './components/LoadingSpinner';
import EmptyState from './components/EmptyState';
import TripSuggestions from './components/TripSuggestions';

const App: React.FC = () => {
    const [prompt, setPrompt] = useState('');
    const [itinerary, setItinerary] = useState<ItineraryOption | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [loadingStatus, setLoadingStatus] = useState('');

    const loadingMessages = [
        "Contacting our AI travel agent...",
        "Planning your flights and accommodation...",
        "Crafting your daily activities...",
        "Finalizing your personalized itinerary...",
        "Just a moment longer, adventure awaits!"
    ];

    useEffect(() => {
        let interval: NodeJS.Timeout | undefined;
        if (isLoading) {
            setLoadingStatus(loadingMessages[0]);
            let i = 1;
            interval = setInterval(() => {
                setLoadingStatus(loadingMessages[i % loadingMessages.length]);
                i++;
            }, 3000);
        }
        return () => {
            if (interval) {
                clearInterval(interval);
            }
        };
    }, [isLoading]);

    const handleSubmit = async (currentPrompt: string) => {
        if (!currentPrompt.trim()) return;
        setIsLoading(true);
        setError(null);
        setItinerary(null);
        try {
            const result = await generateItinerary(currentPrompt);
            if (result.itineraries && result.itineraries.length > 0) {
                setItinerary(result.itineraries[0]);
            } else {
                setError("Sorry, we couldn't generate an itinerary for that request. Please try being more specific.");
            }
        } catch (err) {
            if (err instanceof Error) {
                setError(err.message);
            } else {
                setError("An unexpected error occurred. Please try again.");
            }
        } finally {
            setIsLoading(false);
        }
    };

    const handleSuggestionClick = (suggestion: string) => {
        setPrompt(suggestion);
        handleSubmit(suggestion);
    };

    return (
        <div className="text-slate-300 min-h-screen font-sans">
            <main className="container mx-auto px-4 py-8 max-w-4xl">
                <header className="text-center mb-8">
                    <h1 className="text-5xl font-extrabold text-white [text-shadow:1px_1px_3px_rgba(0,0,0,0.7)]">
                        <span className="text-cyan-400">Safari</span> Trip Planner
                    </h1>
                    <p className="mt-2 text-lg text-slate-400 [text-shadow:1px_1px_2px_rgba(0,0,0,0.8)]">
                        Your AI-powered guide to unforgettable journeys.
                    </p>
                </header>
                <div className="bg-slate-800/50 p-6 rounded-2xl shadow-2xl border border-slate-700 backdrop-blur-sm">
                    <TripInput
                        value={prompt}
                        onChange={setPrompt}
                        onSubmit={() => handleSubmit(prompt)}
                        isLoading={isLoading}
                    />
                    {!isLoading && !itinerary && !error && (
                        <TripSuggestions onSuggestionClick={handleSuggestionClick} />
                    )}
                </div>
                <div className="mt-8">
                    {isLoading && <LoadingSpinner statusText={loadingStatus} />}
                    {error && <div className="bg-red-900/50 border border-red-700 text-red-300 p-4 rounded-lg text-center">{error}</div>}
                    {!isLoading && !error && itinerary && <ItineraryDisplay itineraryData={itinerary} />}
                    {!isLoading && !error && !itinerary && <EmptyState />}
                </div>
            </main>
             <footer className="text-center py-6 text-slate-300 text-sm [text-shadow:1px_1px_2px_rgba(0,0,0,0.8)]">
                <p>Powered by Google Gemini. Itinerary details are generated by AI and may require verification.</p>
            </footer>
        </div>
    );
};

export default App;