import React from 'react';

interface TripInputProps {
    value: string;
    onChange: (value: string) => void;
    onSubmit: () => void;
    isLoading: boolean;
}

const TripInput: React.FC<TripInputProps> = ({ value, onChange, onSubmit, isLoading }) => {
    const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            if (!isLoading) {
                onSubmit();
            }
        }
    };

    return (
        <div className="relative w-full">
            <textarea
                value={value}
                onChange={(e) => onChange(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="e.g., Plan my trip to Bhutan from Dec 15th to Dec 31st with a budget of $2000. Suggest good food and place to visit."
                className="w-full bg-slate-800 border border-slate-700 text-slate-200 rounded-xl p-4 pr-36 focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 transition-all duration-300 resize-none shadow-lg"
                rows={3}
                disabled={isLoading}
            />
            <div className="absolute right-3 top-1/2 -translate-y-1/2 flex flex-col-reverse items-end gap-2">
                 <button
                    onClick={onSubmit}
                    disabled={isLoading || !value.trim()}
                    className="bg-cyan-600 text-white font-bold py-2 px-6 rounded-lg hover:bg-cyan-500 disabled:bg-slate-600 disabled:cursor-not-allowed transition-all duration-300 shadow-md disabled:shadow-none flex items-center justify-center"
                >
                    {isLoading ? (
                        <div className="w-5 h-5 border-2 border-t-2 border-slate-400 border-t-white rounded-full animate-spin"></div>
                    ) : (
                        'Plan Trip'
                    )}
                </button>
                <div className="group relative">
                    <span className="text-xs text-slate-500 hover:text-slate-400 cursor-pointer border-b border-dotted border-slate-500">
                        Important Disclaimer
                    </span>
                    <div className="absolute bottom-full mb-1 right-0 w-80 p-3 bg-slate-900 border border-slate-700 rounded-lg shadow-xl text-xs text-slate-400 opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none z-10">
                        <p>The itinerary and all related information are generated by an AI.</p>
                        <p className="mt-2">Details such as flight/train schedules, prices, and hotel availability are <strong>estimates and not real-time data</strong>.</p>
                        <p className="mt-2"><strong>Please verify all information</strong> from official sources (like airline and hotel websites) before making any bookings.</p>
                         <div className="mt-2 pt-2 border-t border-slate-800">
                             <p><strong>Location Info:</strong> We may ask for your location to use as a default starting point <strong>only if you don't specify one</strong> in your request (e.g., "trip from London...").</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TripInput;